#
# Module manifest for module 'CA.ApiGenerator'
#
# Generated by: RuslanDubas
#
# Generated on: 10/19/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'CA.ApiGenerator.psm1'

# Version number of this module.
ModuleVersion = '1.0.2'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'ad98c9c0-7c84-419c-aa8d-d3df5bfca526'  # Keep your existing GUID from current manifest

# Author of this module
Author = 'Ruslan Dubas'

# Company or vendor of this module
CompanyName = 'Ruslan Dubas'

# Copyright statement for this module
Copyright = '(c) 2025 Ruslan Dubas. All rights reserved.'

# Description of the functionality provided by this module
Description = @'
CA.ApiGenerator automates Clean Architecture API solution generation from existing databases.

Built on Jason Taylor's Clean Architecture template (ca-sln), this module provides:
- Automatic dependency management (auto-installs dbatools, SimplySql, EF Tools, CA template)
- Database-first solution generation for SQL Server and PostgreSQL
- Complete CQRS implementation with MediatR
- Auto-generated REST API controllers for all entities
- FluentValidation for input validation
- Integrated code generator for extending solutions
- Simple PowerShell interface with automated and interactive modes

Generate production-ready Clean Architecture APIs from your database in minutes!
'@

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Minimum version of the .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('New-CAApiSolution')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'CleanArchitecture'
            'API'
            'CodeGeneration'
            'CQRS'
            'MediatR'
            'EntityFramework'
            'DatabaseFirst'
            'SQLServer'
            'PostgreSQL'
            'RestAPI'
            'Automation'
            'DotNet'
            'WebAPI'
            'Microservices'
            'DomainDrivenDesign'
            'FluentValidation'
            'Scaffold'
            'Generator'
            'JasonTaylor'
            'PSEdition_Desktop'
            'PSEdition_Core'
            'Windows'
            'Linux'
            'MacOS'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/RusUsf/CA.ApiGenerator'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/RusUsf/CA.ApiGenerator'

        

        # ReleaseNotes of this module
        ReleaseNotes = @'
## Version 1.0.1

### New Features
- ✅ Automatic dependency management - auto-installs all required dependencies
- ✅ Auto-installs dbatools PowerShell module if missing
- ✅ Auto-installs SimplySql PowerShell module if missing
- ✅ Auto-installs Clean.Architecture.Solution.Template if missing
- ✅ Auto-installs dotnet-ef global tool if missing
- ✅ Validates .NET SDK 9.0 or higher is installed
- ✅ Comprehensive dependency status reporting with color-coded feedback

### Improvements
- Simplified installation - users only need to install .NET 9 SDK manually
- Better error handling with manual installation fallback instructions
- Enhanced user experience with visual feedback during dependency checks
- Improved documentation with troubleshooting section

### Requirements
- PowerShell 5.1 or higher
- .NET SDK 9.0 or higher (manual install required)
- All other dependencies are auto-installed by the module

### Credits
Built on top of:
- Jason Taylor's Clean Architecture Template (ca-sln)
- dbatools by dataplat
- SimplySql by mithrandyr

See full documentation at: https://github.com/RusUsf/CA.ApiGenerator
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        ExternalModuleDependencies = @('dbatools', 'SimplySql')

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/RusUsf/CA.ApiGenerator'

}