#
# Module manifest for module 'CA.ApiGenerator'
#
# Generated by: Ruslan Dubas
#
# Generated on: 11/02/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'CA.ApiGenerator.psm1'

# Version number of this module.
ModuleVersion = '1.0.3'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'ad98c9c0-7c84-419c-aa8d-d3df5bfca526'

# Author of this module
Author = 'Ruslan Dubas'

# Company or vendor of this module
CompanyName = 'Ruslan Dubas'

# Copyright statement for this module
Copyright = '(c) 2024 Ruslan Dubas. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Transform your existing database into a production-ready Clean Architecture API in minutes. Generates complete CQRS implementation, REST controllers, validation, error handling, and integration tests from your database schema. One command. Production-ready code. Supports SQL Server, PostgreSQL, and SQLite.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Minimum version of the .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('New-CAApiSolution')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'API-Generation'
            'Code-Generation'
            'Database-First'
            'Scaffold'
            'Clean-Architecture'
            'CQRS'
            'Entity-Framework'
            'REST-API'
            'SQL-Server'
            'PostgreSQL'
            'DotNet'
            'PowerShell'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/RusUsf/CA.ApiGenerator/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/RusUsf/CA.ApiGenerator'

        # A URL to an icon representing this module.
        IconUri = 'https://ruslandubas.com/ca-api-generator-logo.png'

        # ReleaseNotes of this module
        ReleaseNotes = @'
## Version 1.0.3 - Marketing & Messaging Update

### Improvements
- Enhanced module description with clearer value proposition
- Focused tag selection for better discoverability
- Improved documentation with outcome-focused examples
- Updated README with before/after code examples

### Features (Unchanged)
- Complete Clean Architecture solution generation from existing databases
- CQRS commands/queries with MediatR for all entities
- REST API controllers with full CRUD operations
- FluentValidation for input validation
- Automatic error handling and Swagger documentation
- Integration tests generated automatically
- Multi-database support: SQL Server, PostgreSQL, SQLite

### Requirements
- PowerShell 5.1 or higher
- .NET SDK 9.0 or higher (manual install required)
- All other dependencies auto-installed by the module

### Credits
Built on Jason Taylor's Clean Architecture Template (ca-sln)
Database automation powered by dbatools and SimplySql

See full documentation at: https://github.com/RusUsf/CA.ApiGenerator
'@

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        ExternalModuleDependencies = @('dbatools', 'SimplySql')

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/RusUsf/CA.ApiGenerator'

}